- hosts: all
  gather_facts: yes
  become: true
  tasks:

    - name: Install jenkins
      community.docker.docker_container:
        name: jenkins
        image: jenkins/jenkins:lts-jdk11
        ports:
          - 8080:8080
          - 50000:50000
        volumes:
          - jenkins_home:/var/jenkins_home
        restart_policy: unless-stopped